name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-20.04

    container:
      image: ghcr.io/emqx/emqx-builder/5.0-26:1.13.4-25.1.2-2-ubuntu20.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1000
    - name: Fetch tags
      run: |
        set -x
        WD="$(pwd)"
        git config --global --add safe.directory $WD
        git fetch --tags
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: make eunit
    - name: Run dialyzer
      run: make dialyzer
    # - name: Ensure version consistency
    #   run: ./check_vsns.escript
    # - name: Ensure style
    #   run: ./check-style.sh
